version: '3.8'
services:
  mysql:
    image: mysql:8.0.27
    platform: linux/amd64
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=app
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
